#!/usr/local/bin/bash
NAME=Homura
VER=3.5
ALH=630
GPU=$(glxinfo | grep "OpenGL vendor string")
OSN=$(uname)
NDIR=/usr/home/$USER/.local/share/$NAME
DDIR=$NDIR/Data
ICO=$DDIR/$NAME.png
DATE=$(date)
WINEVER=$(wine --version)

if [[ $USER == *"root"* ]]; then
zenity --info --width=310 --window-icon=$ICO --title="$NAME $VER" --text="$NAME can not be executed as root."
exit
fi

if [ -z "$1" ]
then
CLI=0
fi

if [ ! -d "$NDIR" ]; then
if [[ $CLI == *"0"* ]]; then
mkdir -p $NDIR
zenity --info --width=310 --window-icon=$ICO --title="$NAME $VER - Welcome" --text="Welcome to $NAME. If you have a problem, suggestion, questions or similar, do not hesitate to open an issue on GitHub. Have Fun!"
SC=$(zenity --question --window-icon=$ICO --width 300 --title "$NAME $VER - One time question" --text "Do you want a shortcut of $NAME in your application menu?"; echo $?)
if [[ $SC == *"0"* ]]; then
if [ ! -d "/usr/home/$USER/.local/share/applications" ]; then
mkdir /usr/home/$USER/.local/share/applications
fi
echo "[Desktop Entry]
Comment=
Exec=bash /usr/local/bin/$NAME
Icon=$DDIR/$NAME.png
Categories=Game;
Name=$NAME
StartupNotify=false
Terminal=false
TerminalOptions=
Type=Application
" >> /usr/home/$USER/.local/share/applications/$NAME.desktop 
if [[ $SC == *"1"* ]]; then 
echo "Shortcut will be not created"
fi
if [[ $OSN != "FreeBSD" ]]; then
zenity --info --width=360 --window-icon=$ICO --title="$NAME $VER" --text="You are about to use $NAME on an unsupported system. Please be aware that unexpected errors may occur and that your bug reports can be marked as invaild."
fi
fi
else
echo -e "\e[40;38;5;82mYou must open $NAME first without a command. \e[30;48;5;82m\e[0m"
exit
fi
fi

if [ ! -d "$DDIR" ]; then
mkdir $NDIR/Data
fi

if [ ! -f "$ICO" ]; then
cd $DDIR
curl -O https://vignette.wikia.nocookie.net/madoka/images/7/72/Homura_magical_outfit_1.png/revision/latest/top-crop/width/320/height/320?cb=20160821012353
mv 320?cb=20160821012353 $DDIR/$NAME.png
fi

if [[ $GPU == *"VMware, Inc."* ]]; then
zenity --info --width=420 --window-icon=$ICO --title="$NAME $VER" --text="$NAME have detected that you are using the fallback drivers, please check your gpu driver installation. If you should run $NAME in a virtual machine or you have enabled software rendering then you can ignore this message."
fi

echo -e "\e[32mCopyright (c) 2019-2020, The Homura Project All rights reserved."
echo -e "\e[93mWelcome to $NAME $VER have fun!"
echo -e "\e[3;5;0;92mRunning on $OSN $(uname -r)"
echo -e "\e[3;5;0;36mWine Version: $WINEVER\e[30;48;5;82m\e[0m"
echo -e "\e[3;5;0;31mGPU Info OpenGL:\e[30;48;5;82m\e[0m" && glxinfo | grep OpenGL
echo -e "\e[3;5;0;31mGPU Info Vulkan:\e[30;48;5;82m\e[0m" && vulkaninfo | grep -m 1 "GPU id"

var2=$2
EXECUTABLE=$3

Install() {
INST=$var2
}

Launch() {
LNCH=$var2
}

Uninstall() {
UNST=$var2
}

Winetricks() {
WTR=$var2
}

RunEXE() {
RAEP=$var2
}

"$@"

if [[ $CLI == *"0"* ]]; then
TODO=$(zenity --list --radiolist --window-icon=$ICO  --height=420 --width 300 --title="$NAME $VER" --text "What do you want to do?" --hide-header --column "$NAME" --column "Item" FALSE "Installation" FALSE "Launcher" FALSE "Uninstallation" FALSE "Winetricks" FALSE "Run a executable in prefix" FALSE "Update" FALSE "Applying a fix" FALSE "Open Homura folder" FALSE "Enable logging" FALSE "Other" FALSE "About" FALSE "Exit")
fi

if [[ $CLI == *"0"* ]]; then
if [[ $TODO == *"Installation"* ]]; then
INST=$(zenity --list --radiolist --window-icon=$ICO --height=$ALH --width 300 --title="$NAME $VER - $TODO" --text "What do you want to install?" --hide-header --column "$NAME $VER" --column "Item" FALSE "Steam" FALSE "Blizzard" FALSE "Origin" FALSE "Uplay" FALSE "Teamspeak" FALSE "Clone Hero" FALSE "Drakensang Online" FALSE "Anarchy Online" FALSE "itch" FALSE "GOG Galaxy" FALSE "League of Legends" FALSE "Wargaming Game Center" FALSE "Growtopia" FALSE "Bethesda Launcher" FALSE "Arc" FALSE "Discord" FALSE "Custom Prefix" FALSE "Extras")
fi
fi

if [ ! -d "$NDIR/Games" ]; then
mkdir $NDIR/Games
fi

if [ ! -d "$NDIR/Programs" ]; then
mkdir $NDIR/Programs
fi

cd $DDIR

if [[ $INST == *"Steam"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of Steam\007'
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -o "SteamSetup.exe" "https://steamcdn-a.akamaihd.net/client/installer/SteamSetup.exe" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
echo -e "\e[40;38;5;32mInstalling dotnet40 & arial fonts to fix crashes and missing fonts in several games\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST winetricks dotnet40 arial
echo -e "\e[40;38;5;32mSet prefix to Windows 10 and prevent that the wm decorates the window\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST winetricks win10 windowmanagerdecorated=n
echo -e "\e[40;38;5;32mApplying audio fixes for several games\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST wine reg.exe ADD "HKEY_CURRENT_USER\Software\Wine\AppDefaults\LifeIsStrange.exe" /v "Version" /t "REG_SZ" /d "winxp" /f
WINEPREFIX=$NDIR/Games/$INST wine reg.exe ADD "HKEY_CURRENT_USER\Software\Wine\AppDefaults\helldivers.exe" /v "Version" /t "REG_SZ" /d "winxp" /f
WINEPREFIX=$NDIR/Games/$INST wine reg.exe ADD "HKEY_CURRENT_USER\Software\Wine\AppDefaults\VanHelsing_x86.exe" /v "Version" /t "REG_SZ" /d "winxp" /f
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST wine $DDIR/SteamSetup.exe
echo -e "\e[40;38;5;32mReplacing the shortcut with one that contains the required tweaks\e[30;48;5;82m\e[0m"
rm /usr/home/$USER/.local/share/applications/wine/Programs/Steam/Steam.desktop
echo "[Desktop Entry]
Name=Steam
Exec=env WINEPREFIX="$NDIR/Games/$INST" wine '$NDIR/Games/$INST/drive_c/Program Files/Steam/Steam.exe' -no-browser +open steam://open/minigameslist
Type=Application
StartupNotify=true
Icon=BAC4_steam.0" >> /usr/home/$USER/.local/share/applications/wine/Programs/Steam/Steam.desktop
rm $DDIR/SteamSetup.exe
fi

if [[ $INST == *"Blizzard"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of Blizzard\007'
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -o "Battle.net-Setup-enUS.exe" "http://dist.blizzard.com/downloads/bna-installers/322d5bb9ae0318de3d4cde7641c96425/retail.1/Battle.net-Setup-enUS.exe" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
echo -e "\e[40;38;5;32mSet prefix to Windows 10 and prevent that the wm decorates the window\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST winetricks win10 windowmanagerdecorated=n
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST wine $DDIR/Battle.net-Setup-enUS.exe
rm $DDIR/Battle.net-Setup-enUS.exe
fi

if [[ $INST == *"Origin"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of Origin\007'
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -o "OriginThinSetup.exe" "https://origin-a.akamaihd.net/Origin-Client-Download/origin/legacy/OriginThinSetup.exe" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
echo -e "\e[40;38;5;32mSet prefix to Windows xp because origin dont work with newer versions\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/Origin winetricks winxp
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
zenity --info --width=310 --window-icon=$ICO --title="$NAME $VER - Origin" --text="Dont forget to disable the Origin in-game overlay or you are unable to start a game."
WINEPREFIX=$NDIR/Games/$INST wine $DDIR/OriginThinSetup.exe
rm $DDIR/OriginThinSetup.exe
fi

if [[ $INST == *"Uplay"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of Uplay\007'
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -o "UplayInstaller.exe" "https://ubistatic3-a.akamaihd.net/orbit/launcher_installer/UplayInstaller.exe" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
echo -e "\e[40;38;5;32mSet prefix to Windows 10\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST winetricks win10
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
zenity --info --width=260 --window-icon=$ICO --title="$NAME $VER - Installation of $INST" --text="Before you continue, please make sure that the package x11-fonts/noto-extra is not installed. After installation of $INST you can install it again. "
WINEPREFIX=$NDIR/Games/$INST wine $DDIR/UplayInstaller.exe
rm $DDIR/UplayInstaller.exe
fi

if [[ $INST == *"Teamspeak"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of Teamspeak\007'
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -o "TeamSpeak3-Client-win32-3.3.2.exe" "https://files.teamspeak-services.com/releases/client/3.3.2/TeamSpeak3-Client-win32-3.3.2.exe" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
echo -e "\e[40;38;5;32mSet prefix to Windows 10\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST winetricks win10
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
zenity --info --width=260 --window-icon=$ICO --title="$NAME $VER - Installation of $INST" --text="To get Playback and Capture working set both mods to Direct Sound."
zenity --info --width=260 --window-icon=$ICO --title="$NAME $VER - Installation of $INST" --text="Before you continue, please make sure that the package x11-fonts/noto-extra is installed. After installation of $INST you can remove it again."
WINEPREFIX=$NDIR/Programs/$INST wine $DDIR/TeamSpeak3-Client-win32-3.3.2.exe
rm $DDIR/TeamSpeak3-Client-win32-3.3.2.exe
fi

if [[ $INST == *"Clone Hero"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of Clone Hero\007'
mkdir "$NDIR/Games/$INST"
cd "$NDIR/Games/$INST"
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -o "clonehero-win32.7z" "http://dl.clonehero.net/clonehero-v.23.2.2/clonehero-win32.7z" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
echo -e "\e[40;38;5;32mInstalling arial fonts to fix missing fonts in the controls menu and ingame\e[30;48;5;82m\e[0m"
WINEPREFIX="$NDIR/Games/$INST" winetricks arial
echo -e "\e[40;38;5;32mSet prefix to Windows 10\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST winetricks win10
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
7z x clonehero-win32.7z
rm clonehero-win32.7z
echo -e "\e[40;38;5;32mApplying a fix to prevent game from crashing at start\e[30;48;5;82m\e[0m"
cd clonehero-win32
curl -O https://raw.githubusercontent.com/the-homura-project/homura-database/master/Clone%20Hero/settings.ini
zenity --info --width=500 --window-icon=$ICO --title="$NAME $VER - Clone Hero" --text="If you own a guitar hero controller, you may want to check out the tutorial how to get this controller working: https://forums.freebsd.org/threads/setting-up-guitar-hero-guitars-for-clone-hero-etc-on-freebsd.72953/"
fi

if [[ $INST == *"Drakensang Online"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of Drakensang Online\007'
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -o "dro_setup.exe" "https://drasaonline-481-dwl.bpsecure.com/applet/dro_setup.exe" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
echo -e "\e[40;38;5;32mSet prefix to Windows 10\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST winetricks win10
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
WINEPREFIX="$NDIR/Games/Drakensang Online" wine $DDIR/dro_setup.exe
rm $DDIR/dro_setup.exe
fi

if [[ $INST == *"Anarchy Online"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of Anarchy Online\007'
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -o "AnarchyOnline_EP1.exe" "http://update.anarchy-online.com/download/AO/AnarchyOnline_EP1.exe" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
WINEPREFIX="$NDIR/Games/Anarchy Online" winetricks winxp
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
zenity --info --width=260 --title="$NAME $VER - Installation of Anarchy Online" --text="Please let the installer create an shortcut or you will unable to start the launcher later."
WINEPREFIX="$NDIR/Games/Anarchy Online" wine $DDIR/AnarchyOnline_EP1.exe
rm $DDIR/AnarchyOnline_EP1.exe
fi

if [[ $INST == *"itch"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of itch\007'
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -L -o "windows" "http://nuts.itch.zone/download/windows" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
echo -e "\e[40;38;5;32mSet prefix to Windows 10\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST winetricks win10
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST wine $DDIR/windows
rm $DDIR/windows
fi

if [[ $INST == *"GOG Galaxy"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of GOG Galaxy\007'
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -o "setup_galaxy_1.2.64.2.exe" "https://cdn.gog.com/open/galaxy/client/setup_galaxy_1.2.64.2.exe" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
echo -e "\e[40;38;5;32mSet prefix to Windows 10\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST winetricks win10
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
WINEPREFIX="$NDIR/Games/$INST" wine $DDIR/setup_galaxy_1.2.64.2.exe
if [ -f "/usr/home/$USER/.local/share/applications/wine/Programs/GOG.com/GOG Galaxy/GOG Galaxy.desktop" ]; then
echo -e "\e[40;38;5;32mReplacing the shortcut with one that contains the required tweaks\e[30;48;5;82m\e[0m"
rm "/usr/home/$USER/.local/share/applications/wine/Programs/GOG.com/GOG Galaxy/GOG Galaxy.desktop"
echo "[Desktop Entry]
Name=GOG Galaxy
Exec=$NAME Launch '$INST'
Type=Application
StartupNotify=true
Icon=F77E_GalaxyClient.0" >> "/usr/home/$USER/.local/share/applications/wine/Programs/GOG.com/GOG Galaxy/$INST.desktop"
else 
echo -e "\e[40;38;5;32mNo shortcut was created\e[30;48;5;82m\e[0m"
fi
rm $DDIR/setup_galaxy_1.2.64.2.exe
fi

if [[ $INST == *"League of Legends"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of League of Legends\007'
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -o "live.euw.exe" "https://lol.secure.dyn.riotcdn.net/channels/public/x/installer/current/live.euw.exe" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
echo -e "\e[40;38;5;32mSet prefix to Windows 10\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST winetricks win10
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST wine $DDIR/live.euw.exe
rm $DDIR/live.euw.exe
fi

if [[ $INST == *"Wargaming Game Center"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of Wargaming Game Center\007'
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -L -o "Wargaming_Game_Center_Install_EU.exe" "http://redirect.wargaming.net/WGC/Wargaming_Game_Center_Install_EU.exe" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
WINEPREFIX="$NDIR/Games/$INST" winetricks vcrun2015
WINEPREFIX="$NDIR/Games/$INST" winetricks win7
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
WINEPREFIX="$NDIR/Games/$INST" wine $DDIR/Wargaming_Game_Center_Install_EU.exe
rm $DDIR/Wargaming_Game_Center_Install_EU.exe
fi

if [[ $INST == *"Growtopia"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of Growtopia\007'
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -L -o "Growtopia-Installer.exe" "https://growtopiagame.com/Growtopia-Installer.exe" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
echo -e "\e[40;38;5;32mSet prefix to Windows 10\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST winetricks win10
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST wine $DDIR/Growtopia-Installer.exe
rm $DDIR/Growtopia-Installer.exe
fi

if [[ $INST == *"Bethesda Launcher"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of Bethesda Launcher\007'
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -L -o "BethesdaNetLauncher_Setup.exe" "http://download.cdp.bethesda.net/BethesdaNetLauncher_Setup.exe" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
echo -e "\e[40;38;5;32mSet prefix to Windows 10\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST winetricks win10
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
WINEPREFIX="$NDIR/Games/$INST" wine $DDIR/BethesdaNetLauncher_Setup.exe
rm $DDIR/BethesdaNetLauncher_Setup.exe
fi

if [[ $INST == *"Arc"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of Arc\007'
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -o "download" "https://www.arcgames.com/download" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
echo -e "\e[40;38;5;32mSet prefix to Windows 10\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST winetricks win10
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$INST wine $DDIR/download
rm $DDIR/download
fi

if [[ $INST == *"Discord"* ]]; then
echo $'\033]30;Homura 3.5 - Installation of Discord\007'
mkdir -p $NDIR/Programs/$INST
mkdir -p $NDIR/Programs/$INST/Discord
cd $NDIR/Programs/$INST/Discord
echo -e "\e[40;38;5;82mDownloading $INST\e[30;48;5;82m\e[0m"
curl -o "Discord.tar" "https://homura.magzu.net/dl/Discord.tar" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $INST" --title "$NAME $VER $TODO $INST" --window-icon=$ICO
echo -e "\e[40;38;5;82mSetup prefix\e[30;48;5;82m\e[0m"
echo -e "\e[40;38;5;32mInstallation of dotnet472 and setting prefix to Windows 10\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Programs/$INST winetricks dotnet472 win10
echo -e "\e[40;38;5;82mInstalling $INST\e[30;48;5;82m\e[0m"
tar -xf Discord.tar
rm Discord.tar
fi

if [[ $INST == *"Custom Prefix"* ]]; then
echo $'\033]30;Homura Installation of Custom Prefix\007'
PREFIXNAME=$(zenity --window-icon=$ICO --title="Create a custom prefix" --text "How your prefix should be called?" --entry --width=260) 
if [ ! -d "$NDIR/Custom Prefixes" ]; then
mkdir "$NDIR/Custom Prefixes"
fi
if [ -z "$PREFIXNAME" ]
then
zenity --info --width=310 --window-icon=$ICO --title="Create a custom prefix" --text="No name was given, the creation will be aborted now."
else
mkdir -p "$NDIR/Custom Prefixes/$PREFIXNAME"
cd "$NDIR/Custom Prefixes/$PREFIXNAME"
zenity --info --width=260 --title="Create a custom prefix" --text="Now you need to select the executable that do you want to use in this prefix."
EXECUTABLE="$(zenity --file-selection --title="Choose your executable")"
ENV=$(zenity --title="Environment variable" --text "Do you need an environment variable for your executable? (for example DXVK_HUD=1) if not leave it blank." --entry --window-icon=$ICO --width=260) 
SPM=$(zenity --title="Startparameter" --text "Do you need an startparameter for your executable? (for example -console) if not leave it blank." --entry --window-icon=$ICO --width=260) 
echo "$ENV WINEPREFIX='$NDIR/Custom Prefixes/$PREFIXNAME' wine '$EXECUTABLE' $SPM" >> start.sh
fi
fi

if [[ $INST == *"Extras"* ]]; then
ETS=$(zenity --list --radiolist --window-icon=$ICO --height=200 --width=400  --title="$NAME $VER - $INST" --text "What extra do you want to install?" --hide-header --column "$NAME $VER" --column "Item" FALSE "Torchlight German Patch" FALSE "Left 4 Gore")

if [[ $ETS == *"Torchlight German Patch"* ]]; then
echo $'\033]30;Torchlight German Patch\007'
TGPH=$(zenity --list --radiolist --window-icon=$ICO --height=100 --width=360 --title="$NAME $VER $ETS" --text "What version?" --hide-header --column "$NAME $VER" --column "Item" FALSE "German Patch V3 (Steam-Edition)" FALSE "German Patch V5 (GOG/Epic-Edition)")

if [[ $TGPH == *"German Patch V3 (Steam-Edition)"* ]]; then
echo -e "\e[40;38;5;82mDownloading $TGPH\e[30;48;5;82m\e[0m"
curl -o "Torchlight_GerPatchV3_Steam.zip" "https://homura.magzu.net/games/Torchlight_GerPatchV3_Steam.zip" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $TGPH" --title "$NAME $VER $TODO $TGPH" --window-icon=$ICO
unzip Torchlight_GerPatchV3_Steam.zip
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/Steam wine $DDIR/Torchlight_GerPatchV3_Steam.exe
rm Torchlight_GerPatchV3_Steam.exe
rm Torchlight_GerPatchV3_Steam.zip
fi

if [[ $TGPH == *"German Patch V5 (GOG/Epic-Edition)"* ]]; then
echo -e "\e[40;38;5;82mDownloading $TGPH\e[30;48;5;82m\e[0m"
curl -o "Torchlight_GerPatchV5_GOGEPIC.zip" "https://homura.magzu.net/games/Torchlight_GerPatchV5_GOGEPIC.zip" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $TGPH" --title "$NAME $VER $TODO $TGPH" --window-icon=$ICO
unzip Torchlight_GerPatchV5_GOGEPIC.zip
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
WINEPREFIX="$NDIR/Games/GOG Galaxy" wine $DDIR/Torchlight_GerPatchV5_GOGEPIC.exe
rm Torchlight_GerPatchV5_GOGEPIC.exe
rm Torchlight_GerPatchV5_GOGEPIC.zip
fi
fi

if [[ $ETS == *"Left 4 Gore"* ]]; then
echo -e "\e[40;38;5;82mDownloading $ETS\e[30;48;5;82m\e[0m"
mkdir -p $NDIR/Extras
cd $NDIR/Extras
curl -o "left4gore-2.3-windows.zip" "http://www.left4gore.com/dist/left4gore-2.3-windows.zip" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --auto-close --text "Downloading $ETS" --title "$NAME $VER $TODO $ETS" --window-icon=$ICO
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
unzip left4gore-2.3-windows.zip
rm left4gore-2.3-windows.zip
fi
fi

if [[ $CLI == *"0"* ]]; then
if [[ $TODO == *"Launcher"* ]]; then
LNCH=$(zenity --list --radiolist --window-icon=$ICO --height=$ALH --width 300 --title="$NAME $VER - $TODO" --text "What do you want to launch?" --hide-header --column "$NAME $VER" --column "Item" FALSE "Steam" FALSE "Blizzard" FALSE "Origin" FALSE "Uplay" FALSE "Teamspeak" FALSE "Clone Hero" FALSE "Drakensang Online" FALSE "Anarchy Online" FALSE "itch" FALSE "GOG Galaxy" FALSE "League of Legends" FALSE "Wargaming Game Center" FALSE "Growtopia" FALSE "Bethesda Launcher" FALSE "Arc" FALSE "Discord" FALSE "Left 4 Gore" FALSE "Custom Prefix")
fi
fi

CCKGPDIR=$NDIR/Games/$LNCH

if [[ $CCKGPDIR == *"$NDIR/Games/Teamspeak"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Discord"* ]] ; then
if [ ! -d "$NDIR/Programs/$LNCH" ]; then
if [[ $CLI == *"0"* ]]; then
zenity --info --width=200 --window-icon=$ICO --title="$NAME $VER - $LNCH" --text="$LNCH is not installed."
exec $NAME
fi
echo -e "\e[40;38;5;82m$LNCH is not installed.\e[30;48;5;82m\e[0m"
exit
fi
fi

if [[ $CCKGPDIR == *"$NDIR/Games/Left 4 Gore"* ]]; then
if [ ! -d "$NDIR/Extras/left4gore-2.3-windows" ]; then
if [[ $CLI == *"0"* ]]; then
zenity --info --width=200 --window-icon=$ICO --title="$NAME $VER - $LNCH" --text="$LNCH is not installed."
exec $NAME
fi
echo -e "\e[40;38;5;82m$LNCH is not installed.\e[30;48;5;82m\e[0m"
exit
fi
fi

if [[ $CCKGPDIR == *"$NDIR/Games/Steam"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Blizzard"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Origin"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Uplay"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Clone Hero"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Drakensang Online"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/itch"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Anarchy Online"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/GOG Galaxy"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/League of Legends"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Wargaming Game Center"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Wargaming Game Center"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Growtopia"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Bethesda Launcher"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Wargaming Game Center"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Arc"* ]] ; then
if [ ! -d "$NDIR/Games/$LNCH" ]; then
if [[ $CLI == *"0"* ]]; then
zenity --info --width=200 --window-icon=$ICO --title="$NAME $VER - $LNCH" --text="$LNCH is not installed."
exec $NAME
fi
echo -e "\e[40;38;5;82m$LNCH is not installed.\e[30;48;5;82m\e[0m"
exit
fi
fi

if [[ $LNCH == *"Steam"* ]]; then
echo $'\033]30;Steam\007'        
WINEPREFIX=$NDIR/Games/$LNCH wine "$NDIR/Games/$LNCH/drive_c/Program Files/Steam/Steam.exe" -no-browser +open steam://open/minigameslist
fi

if [[ $LNCH == *"Blizzard"* ]]; then
echo $'\033]30;Blizzard\007'
WINEPREFIX=$NDIR/Games/$LNCH wine "$NDIR/Games/$LNCH/drive_c/Program Files/Battle.net/Battle.net.exe"
fi

if [[ $LNCH == *"Origin"* ]]; then
echo $'\033]30;Origin\007'
WINEPREFIX=$NDIR/Games/$LNCH wine "$NDIR/Games/$LNCH/drive_c/Program Files/Origin/Origin.exe"
fi

if [[ $LNCH == *"Uplay"* ]]; then
echo $'\033]30;Uplay\007'
WINEPREFIX=$NDIR/Games/$LNCH wine "$NDIR/Games/$LNCH/drive_c/Program Files/Ubisoft/Ubisoft Game Launcher/Uplay.exe"
fi

if [[ $LNCH == *"Teamspeak"* ]]; then
echo $'\033]30;Teamspeak\007'
WINEPREFIX=$NDIR/Programs/$LNCH wine "$NDIR/Programs/$LNCH/drive_c/Program Files/TeamSpeak 3 Client/ts3client_win32.exe"
fi

if [[ $LNCH == *"Clone Hero"* ]]; then
echo $'\033]30;Clone Hero\007'
WINEPREFIX="$NDIR/Games/$LNCH" wine "$NDIR/Games/$LNCH/clonehero-win32/Clone Hero.exe"
fi

if [[ $LNCH == *"Drakensang Online"* ]]; then
echo $'\033]30;Drakensang Online\007'
WINEPREFIX="$NDIR/Games/$LNCH" wine "$NDIR/Games/$LNCH/drive_c/Program Files/Drakensang Online/thinclient.exe"
fi

if [[ $LNCH == *"Anarchy Online"* ]]; then
echo $'\033]30;Anarchy Online\007'
env WINEPREFIX="$NDIR/Games/$LNCH" wine C:\\windows\\command\\start.exe /Unix $NDIR/Games/Anarchy\ Online/dosdevices/c:/ProgramData/Microsoft/Windows/Start\ Menu/Programs/Anarchy\ Online/Anarchy\ Online.lnk
fi

if [[ $LNCH == *"itch"* ]]; then
echo $'\033]30;itch\007'
ITCHVER=$(ls -a "$NDIR/Games/$LNCH/drive_c/users/$USER/Local Settings/Application Data/itch/" | grep "app-")
WINEPREFIX=$NDIR/Games/$LNCH wine "$NDIR/Games/$LNCH/drive_c/users/$USER/Local Settings/Application Data/itch/$ITCHVER/itch.exe"
fi

if [[ $LNCH == *"GOG Galaxy"* ]]; then
echo $'\033]30;GOG Galaxy\007'
WINEPREFIX="$NDIR/Games/$LNCH" wine "$NDIR/Games/$LNCH/drive_c/Program Files/GOG Galaxy/GalaxyClient.exe" /runWithoutUpdating /deelevated
fi

if [[ $LNCH == *"League of Legends"* ]]; then
echo $'\033]30;League of Legends\007'
WINEPREFIX="$NDIR/Games/$LNCH" wine "$NDIR/Games/$LNCH/drive_c/Riot Games/League of Legends/LeagueClient.exe"
fi

if [[ $LNCH == *"Wargaming Game Center"* ]]; then
echo $'\033]30;Wargaming Game Center\007'
WINEPREFIX="$NDIR/Games/$LNCH" wine "$NDIR/Games/$LNCH/drive_c/Program Files/Wargaming.net/GameCenter/wgc.exe"
fi

if [[ $LNCH == *"Growtopia"* ]]; then
echo $'\033]30;Growtopia\007'
WINEPREFIX=$NDIR/Games/$LNCH wine "$NDIR/Games/$LNCH/drive_c/users/$USER/Local Settings/Application Data/Growtopia/Growtopia.exe"
fi

if [[ $LNCH == *"Bethesda Launcher"* ]]; then
echo $'\033]30;Bethesda Launcher\007'
WINEPREFIX="$NDIR/Games/$LNCH" wine "$NDIR/Games/$LNCH/drive_c/Program Files/Bethesda.net Launcher/BethesdaNetLauncher.exe"
fi

if [[ $LNCH == *"Arc"* ]]; then
echo $'\033]30;Arc\007'
WINEPREFIX=$NDIR/Games/$LNCH wine "$NDIR/Games/$LNCH/drive_c/Program Files/Arc/ArcLauncher.exe"
fi

if [[ $LNCH == *"Discord"* ]]; then
echo $'\033]30;Discord\007'
WINEPREFIX=$NDIR/Programs/$LNCH wine $NDIR/Programs/$LNCH/Discord/app-0.0.305/Discord.exe
fi

if [[ $LNCH == *"Left 4 Gore"* ]]; then
echo $'\033]30;Left 4 Gore\007'
WINEPREFIX=$NDIR/Games/Steam wine "$NDIR/Extras/left4gore-2.3-windows/left4gore.exe"
fi

if [[ $LNCH == *"Custom Prefix"* ]]; then
if [ ! "$(ls -A "/usr/home/$USER/.local/share/$NAME/Custom Prefixes")" ]
then
zenity --info --width=310 --window-icon=$ICO --title="$NAME $VER - $LNCH" --text="There is no custom prefix installed"
else
cd "$NDIR/Custom Prefixes"
PREFIXNAME=$(zenity --file-selection --directory --title="Choose your prefix" --filename="/usr/home/$USER/.local/share/$NAME/Custom Prefixes/")
if [ -z "$PREFIXNAME" ]
then
zenity --info --width=310 --window-icon=$ICO --title="$NAME $VER - $TODO" --text="There was no custom prefix selected."
else
echo $'\033]30;$PREFIXNAME\007'
bash "$PREFIXNAME/start.sh"
fi
fi
fi

if [[ $CLI == *"0"* ]]; then
if [[ $TODO == *"Uninstallation"* ]]; then
UNST=$(zenity --list --radiolist --window-icon=$ICO --height=$ALH --width 300 --title="$NAME $VER - $TODO" --text "What do you want to uninstall?" --hide-header --column "$NAME" --column "Item" FALSE "Steam" FALSE "Blizzard" FALSE "Origin" FALSE "Uplay" FALSE "Teamspeak" FALSE "Clone Hero" FALSE "Drakensang Online" FALSE "Anarchy Online" FALSE "itch" FALSE "GOG Galaxy" FALSE "League of Legends" FALSE "Wargaming Game Center" FALSE "Growtopia" FALSE "Bethesda Launcher" FALSE "Arc" FALSE "Discord" FALSE "Left 4 Gore" FALSE "Custom Prefix")
fi
fi

CCKGPDIR=$NDIR/Games/$UNST

if [[ $CCKGPDIR == *"$NDIR/Games/Teamspeak"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Discord"* ]] ; then
if [ ! -d "$NDIR/Programs/$UNST" ]; then
if [[ $CLI == *"0"* ]]; then
zenity --info --width=400 --window-icon=$ICO --title="$NAME $VER - $UNST" --text="You can not uninstall something that you dont have installed :)"
exec $NAME
fi
echo -e "\e[40;38;5;82mYou can not uninstall something that you dont have installed :)\e[30;48;5;82m\e[0m"
exit
fi
fi

if [[ $CCKGPDIR == *"$NDIR/Games/Left 4 Gore"* ]]; then
if [ ! -d "$NDIR/Extras/left4gore-2.3-windows" ]; then
if [[ $CLI == *"0"* ]]; then
zenity --info --width=400 --window-icon=$ICO --title="$NAME $VER - $UNST" --text="You can not uninstall something that you dont have installed :)"
exec $NAME
fi
echo -e "\e[40;38;5;82mYou can not uninstall something that you dont have installed :)\e[30;48;5;82m\e[0m"
exit
fi
fi

if [[ $CCKGPDIR == *"$NDIR/Games/Custom Prefix"* ]]; then
echo $'\033]30;Custom Prefix\007'
fi

if [[ $CCKGPDIR == *"$NDIR/Games/Steam"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Blizzard"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Origin"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Uplay"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Clone Hero"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Drakensang Online"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/itch"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Anarchy Online"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/GOG Galaxy"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/League of Legends"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Wargaming Game Center"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Wargaming Game Center"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Growtopia"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Bethesda Launcher"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Wargaming Game Center"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Arc"* ]] ; then
if [ ! -d "$NDIR/Games/$UNST" ]; then
if [[ $CLI == *"0"* ]]; then
zenity --info --width=400 --window-icon=$ICO --title="$NAME $VER - $UNST" --text="You can not uninstall something that you dont have installed :)"
exec $NAME
fi
echo -e "\e[40;38;5;82mYou can not uninstall something that you dont have installed :)\e[30;48;5;82m\e[0m"
exit
fi
fi

if [[ $UNST == *"Steam"* ]]; then
rm -d -r "$NDIR/Games/$UNST"
rm -d -r /usr/home/$USER/.local/share/applications/wine/Programs/$UNST
rm /usr/home/$USER/Desktop/$UNST.desktop
fi

if [[ $UNST == *"Blizzard"* ]]; then
rm -d -r "$NDIR/Games/$UNST"
rm -d -r /usr/home/$USER/.local/share/applications/wine/Programs/Battle.net
rm -d -r /usr/home/$USER/Desktop/Battle.net.desktop
fi

if [[ $UNST == *"Origin"* ]]; then
rm -d -r "$NDIR/Games/$UNST"
rm -d -r /usr/home/$USER/.local/share/applications/wine/Programs/$UNST
rm /usr/home/$USER/Desktop/$UNST.desktop
fi

if [[ $UNST == *"Uplay"* ]]; then
rm -d -r "$NDIR/Games/$UNST"
rm -d -r /usr/home/$USER/.local/share/applications/wine/Programs/Ubisoft
rm /usr/home/$USER/Desktop/$UNST.desktop
rm /usr/home/$USER/Desktop/$UNST.lnk 
fi

if [[ $UNST == *"Teamspeak"* ]]; then
rm -d -r $NDIR/Programs/$UNST
rm "/usr/home/$USER/.local/share/applications/wine/Programs/TeamSpeak 3 Client.desktop"
fi

if [[ $UNST == *"Clone Hero"* ]]; then
rm -d -r "$NDIR/Games/$UNST"
rm "/usr/home/$USER/.local/share/applications/$CS.desktop"
fi

if [[ $UNST == *"Drakensang Online"* ]]; then
rm -d -r "$NDIR/Games/$UNST"
rm -d -r "/usr/home/$USER/.local/share/applications/wine/Programs/$UNST"
rm "/usr/home/$USER/Desktop/$UNST.desktop"
rm "/usr/home/$USER/Desktop/$UNST.lnk"
fi

if [[ $UNST == *"Anarchy Online"* ]]; then
rm -d -r "$NDIR/Games/$UNST"
rm -d -r "/usr/home/$USER/.local/share/applications/wine/Programs/$UNST"
rm "/usr/home/$USER/Desktop/$UNST.desktop"
fi

if [[ $UNST == *"itch"* ]]; then
rm -d -r "$NDIR/Games/$UNST"
rm -d -r "/usr/home/$USER/.local/share/applications/wine/Programs/Itch Corp"
fi

if [[ $UNST == *"League of Legends"* ]]; then
rm -d -r "$NDIR/Games/$UNST"
rm "/usr/home/$USER/.local/share/applications/$UNST.desktop"
rm $DDIR/icon.png
fi

if [[ $UNST == *"GOG Galaxy"* ]]; then
rm -d -r "$NDIR/Games/$UNST"
rm -d -r /usr/home/$USER/.local/share/applications/wine/Programs/GOG.com
rm -d -r "/usr/home/$USER/Desktop/$UNST.desktop"
fi

if [[ $UNST == *"Wargaming Game Center"* ]]; then
rm -d -r "$NDIR/Games/$UNST"
rm -d -r /usr/home/$USER/.local/share/applications/wine/Programs/Wargaming.net
rm "/usr/home/$USER/Desktop/Game Center.desktop"
fi

if [[ $UNST == *"Growtopia"* ]]; then
rm -d -r "$NDIR/Games/$UNST"
rm -d -r /usr/home/$USER/.local/share/applications/wine/Programs/$UNST
rm /usr/home/$USER/Desktop/Growtopia.desktop
fi

if [[ $UNST == *"Bethesda Launcher"* ]]; then
rm -d -r "$NDIR/Games/$UNST"
rm -d -r "/usr/home/$USER/.local/share/applications/wine/Programs/Bethesda.net Launcher"
fi

if [[ $UNST == *"Arc"* ]]; then
rm -d -r "$NDIR/Games/$UNST"
rm -d -r "/usr/home/$USER/.local/share/applications/wine/Programs/Perfect World Entertainment"
fi

if [[ $UNST == *"Discord"* ]]; then
rm -d -r $NDIR/Programs/$UNST
rm /usr/home/$USER/.local/share/applications/$UNST.desktop
fi

if [[ $UNST == *"Left 4 Gore"* ]]; then
rm -d -r /usr/home/$USER/.local/share/$NAME/Extras/left4gore-2.3-windows
rm "/usr/home/$USER/.local/share/applications/$UNST.desktop"
fi

if [[ $UNST == *"Custom Prefix"* ]]; then
cd "$NDIR/Custom Prefixes"
PREFIXNAME=$(zenity --file-selection --directory --title="Choose your prefix" --filename="/usr/home/$USER/.local/share/$NAME/Custom Prefixes/")
if [ -z "$PREFIXNAME" ]
then
zenity --info --width=310 --window-icon=$ICO --title="$NAME $VER - $TODO" --text="There was no custom prefix selected."
else
rm -r -d "$PREFIXNAME"
fi
fi

if [[ $CLI == *"0"* ]]; then
if [[ $TODO == *"Winetricks"* ]]; then
WTR=$(zenity --list --radiolist --window-icon=$ICO --height=$ALH --title="$NAME $VER - $TODO" --text "In what prefix do you want to open winetricks?" --hide-header --column "$NAME" --column "Item" FALSE "Steam" FALSE "Blizzard" FALSE "Origin" FALSE "Uplay" FALSE "Teamspeak" FALSE "Clone Hero" FALSE "Drakensang Online" FALSE "Anarchy Online" FALSE "itch" FALSE "GOG Galaxy" FALSE "League of Legends" FALSE "Wargaming Game Center" FALSE "Growtopia" FALSE "Bethesda Launcher" FALSE "Arc" FALSE "Discord" FALSE "Custom Prefix")
fi
fi

# If a prefix dont exists, winetricks will create a prefix instead. We leave this like this, if someone wants to change the prefix before installing the application.

if [[ $WTR == *"Steam"* ]] || [[ $WTR == *"Blizzard"* ]] || [[ $WTR == *"Origin"* ]] || [[ $WTR == *"Uplay"* ]] || [[ $WTR == *"Clone Hero"* ]] || [[ $WTR == *"Drakensang Online"* ]] || [[ $WTR == *"itch"* ]] || [[ $WTR == *"Anarchy Online"* ]] || [[ $WTR == *"GOG Galaxy"* ]] || [[ $WTR == *"League of Legends"* ]] || [[ $WTR == *"Wargaming Game Center"* ]] || [[ $WTR == *"Wargaming Game Center"* ]] || [[ $WTR == *"Growtopia"* ]] || [[ $WTR == *"Bethesda Launcher"* ]] || [[ $WTR == *"Wargaming Game Center"* ]] || [[ $WTR == *"Arc"* ]] ; then
WINEPREFIX=$NDIR/Games/$WTR winetricks
fi

if [[ $WTR == *"Teamspeak"* ]]; then
WINEPREFIX=$NDIR/Programs/$WTR winetricks
fi

if [[ $WTR == *"Discord"* ]]; then
WINEPREFIX=$NDIR/Programs/$WTR winetricks
fi

if [[ $WTR == *"Custom Prefix"* ]]; then
cd "$NDIR/Custom Prefixes"
PREFIXNAME=$(zenity --file-selection --directory --title="Choose your prefix" --filename="/usr/home/$USER/.local/share/$NAME/Custom Prefixes/")
if [ -z "$PREFIXNAME" ]
then
zenity --info --width=310 --window-icon=$ICO --title="$NAME $VER - $TODO" --text="There was no custom prefix selected."
else
WINEPREFIX="$PREFIXNAME" winetricks
fi
fi

if [[ $CLI == *"0"* ]]; then
if [[ $TODO == *"Run a executable in prefix"* ]]; then
RAEP=$(zenity --list --radiolist --window-icon=$ICO --height=$ALH --title="$NAME $VER - $TODO" --text "In what prefix do you want open your executable?" --hide-header --column "$NAME" --column "Item" FALSE "Steam" FALSE "Blizzard" FALSE "Origin" FALSE "Uplay" FALSE "Teamspeak" FALSE "Clone Hero" FALSE "Drakensang Online" FALSE "Anarchy Online" FALSE "itch" FALSE "GOG Galaxy" FALSE "League of Legends" FALSE "Wargaming Game Center" FALSE "Growtopia" FALSE "Bethesda Launcher" FALSE "Arc" FALSE "Discord" FALSE "Custom Prefix")
EXECUTABLE="$(zenity --file-selection --title="Choose your executable")"
fi
fi

if [[ $RAEP == *"Steam"* ]] || [[ $RAEP == *"Blizzard"* ]] || [[ $RAEP == *"Origin"* ]] || [[ $RAEP == *"Uplay"* ]] || [[ $RAEP == *"Clone Hero"* ]] || [[ $RAEP == *"Drakensang Online"* ]] || [[ $RAEP == *"itch"* ]] || [[ $RAEP == *"Anarchy Online"* ]] || [[ $RAEP == *"GOG Galaxy"* ]] || [[ $WTR == *"League of Legends"* ]] || [[ $WTR == *"Wargaming Game Center"* ]] || [[ $WTR == *"Wargaming Game Center"* ]] || [[ $RAEP == *"Growtopia"* ]] || [[ $RAEP == *"Bethesda Launcher"* ]] || [[ $RAEP == *"Wargaming Game Center"* ]] || [[ $RAEP == *"Arc"* ]] ; then
WINEPREFIX="$NDIR/Games/$RAEP" wine "$EXECUTABLE"
fi

if [[ $RAEP == *"Teamspeak"* ]]; then
WINEPREFIX=$NDIR/Programs/$RAEP wine "$EXECUTABLE"
fi

if [[ $RAEP == *"Discord"* ]]; then
WINEPREFIX=$NDIR/Programs/$RAEP wine "$EXECUTABLE"
fi

if [[ $RAEP == *"Custom Prefix"* ]]; then
cd "$NDIR/Custom Prefixes"
PREFIXNAME=$(zenity --file-selection --directory --title="Choose your prefix" --filename="/usr/home/$USER/.local/share/$NAME/Custom Prefixes/")
if [ -z "$PREFIXNAME" ]
then
zenity --info --width=310 --window-icon=$ICO --title="$NAME $VER - $TODO" --text="There was no custom prefix selected."
else
WINEPREFIX="$NDIR/Custom Prefixes/$PREFIXNAME" wine "$EXECUTABLE"
fi
fi

if [[ $TODO == *"Update"* ]]; then
UPDE=$(zenity --list --radiolist --window-icon=$ICO --height=250 --width 250 --title="$NAME $VER - $TODO" --text "What do you want to update?" --hide-header --column "$NAME" --column "Item" FALSE "Teamspeak" FALSE "Growtopia" FALSE "Custom Prefix executable")

if [[ $UPDE == *"Teamspeak"* ]]; then
if [ ! -d "$NDIR/Programs/$UPDE" ]; then
zenity --info --width=400 --window-icon=$ICO --title="$NAME $VER - $UPDE" --text="You can not update something what is not installed :)"
else
WINEPREFIX=$NDIR/Programs/$UPDE wine "$NDIR/Programs/$UPDE/drive_c/Program Files/TeamSpeak 3 Client/update.exe"
kill ts3client_win32.exe
fi
fi

if [[ $UPDE == *"Growtopia"* ]]; then
if [ ! -d "$NDIR/Games/$UPDE" ]; then
zenity --info --width=400 --window-icon=$ICO --title="$NAME $VER - $UPDE" --text="You can not update something what is not installed :)"
else
cd $DDIR
curl -L -o "Growtopia-Installer.exe" "https://growtopiagame.com/Growtopia-Installer.exe" 2>&1 | stdbuf -oL tr '\r' '\n' | sed -u 's/^ *\([0-9][0-9]*\).*\( [0-9].*$\)/\1\\:\2/' | zenity --progress --text "Downloading $UPDE" --title "$NAME $VER $TODO $INST"
echo -e "\e[40;38;5;82mStarting installer\e[30;48;5;82m\e[0m"
WINEPREFIX=$NDIR/Games/$UPDE wine $DDIR/Growtopia-Installer.exe
rm $DDIR/Growtopia-Installer.exe
fi
fi

if [[ $UPDE == *"Custom Prefix executable"* ]]; then
echo $'\033]30;Update Custom Prefix executable\007'
cd "$NDIR/Custom Prefixes"
PREFIXNAME=$(zenity --file-selection --directory --title="Choose your prefix" --filename="/usr/home/$USER/.local/share/$NAME/Custom Prefixes/")
if [ -z "$PREFIXNAME" ]
then
zenity --info --width=310 --window-icon=$ICO --title="$NAME $VER - $TODO" --text="There was no custom prefix selected."
else
EXECUTABLE="$(zenity --file-selection --title="Choose your executable")"
ENV=$(zenity --title="Environment variable" --text "Do you need an environment variable for your executable? (for example DXVK_HUD=1) if not leave it blank." --entry --window-icon=$ICO --width=260)
SPM=$(zenity --title="Startparameter" --text "Do you need an startparameter for your executable? (for example -console) if not leave it blank." --entry --window-icon=$ICO --width=260) 
cd "$PREFIXNAME"
rm start.sh
echo "$ENV WINEPREFIX='$PREFIXNAME' wine '$EXECUTABLE' $SPM" >> start.sh
fi
fi
fi

if [[ $TODO == *"Applying a fix"* ]]; then
AAF=$(zenity --list --radiolist --window-icon=$ICO  --height=200 --width 350 --title="$NAME $VER" --text "What fix do you want to apply?" --hide-header --column "$NAME" --column "Item" FALSE "Fix of blackscreen in Anno 1404 (Steam)")

if [[ $AAF == *"Fix of blackscreen in Anno 1404 (Steam)"* ]]; then
if [ ! -d "/usr/home/$USER/.local/share/Homura/Games/Steam/drive_c/Program Files/Steam/steamapps/common/Anno 1404" ]; then
zenity --info --window-icon=$ICO --width=300 --title="$NAME $VER - $AAF" --text="Please install the game first."
else
cd "/usr/home/$USER/.local/share/Homura/Games/Steam/drive_c/Program Files/Steam/steamapps/common/Anno 1404"
curl -O https://raw.githubusercontent.com/the-homura-project/homura-database/master/Anno%201404/Engine.ini
fi
fi
fi

if [[ $TODO == *"Open Homura folder"* ]]; then
xdg-open $NDIR
fi

if [[ $TODO == *"Enable logging"* ]]; then
mkdir -p $NDIR/Logs
cd $NDIR/Logs
zenity --info --window-icon=$ICO --width=300 --title="$NAME $VER - About" --text="Logging for this session has been enabled, you will later find the log file in the log folder."
bash $NAME >> "$DATE.log" 2>&1
notify-send "The logging have been quit."
fi

if [[ $TODO == *"Other"* ]]; then
OTR=$(zenity --list --radiolist --window-icon=$ICO --height=250 --width 250 --title="$NAME $VER - $TODO" --text "What do you want to do?" --hide-header --column "$NAME" --column "Item" FALSE "Use software rendering" FALSE "Delete & reset everything" FALSE "Create a shortcut" FALSE "GitHub page")

if [[ $OTR == *"Use software rendering"* ]]; then
LIBGL_ALWAYS_SOFTWARE=1 $NAME
zenity --notification --window-icon=$ICO --text "You are using now hardware rendering again."
fi

if [[ $OTR == *"Delete & reset everything"* ]]; then
DRQ=$(zenity --question --window-icon=$ICO --width 300 --title "$NAME $VER - $OTR" --text "Do you really want to delete and reset everything? ／人◕ ‿‿ ◕人＼"; echo $?)
if [[ $DRQ == *"0"* ]]; then
$NAME Uninstall Steam
$NAME Uninstall Blizzard
$NAME Uninstall Origin
$NAME Uninstall Uplay
$NAME Uninstall Teamspeak
$NAME Uninstall "Clone Hero"
$NAME Uninstall "Drakensang Online"
$NAME Uninstall "Anarchy Online"
$NAME Uninstall itch
$NAME Uninstall "GOG Galaxy"
$NAME Uninstall "League of Legends"
$NAME Uninstall "Wargaming Game Center"
$NAME Uninstall Growtopia
$NAME Uninstall "Bethesda Launcher"
$NAME Uninstall Arc
$NAME Uninstall Discord
$NAME Uninstall "Left 4 Gore"
rm -r -d $NDIR
if [ -f "/usr/home/$USER/.local/share/applications/$NAME.desktop" ]; then
rm "/usr/home/$USER/.local/share/applications/$NAME.desktop"
else 
echo -e "\e[40;38;5;32mNo shortcut was created\e[30;48;5;82m\e[0m"
fi
zenity --info --window-icon=$ICO --width=200 --title="$NAME $VER - $OTR" --text="All files of $NAME have been deleted, we hope you had a good time."
exit
fi
fi

if [[ $OTR == *"Create a shortcut"* ]]; then
CS=$(zenity --list --radiolist --window-icon=$ICO --height=$ALH --width 300 --title="$NAME $VER - $OTR" --text "What shortcut do you want to create?" --hide-header --column "$NAME $VER" --column "Item" FALSE "Steam" FALSE "Blizzard" FALSE "Origin" FALSE "Uplay" FALSE "Teamspeak" FALSE "Clone Hero" FALSE "Drakensang Online" FALSE "Anarchy Online" FALSE "itch" FALSE "GOG Galaxy" FALSE "League of Legends" FALSE "Wargaming Game Center" FALSE "Growtopia" FALSE "Bethesda Launcher" FALSE "Arc" FALSE "Discord" FALSE "Left 4 Gore" FALSE "Custom Prefix")

CCKGPDIR=$NDIR/Games/$CS

if [[ $CCKGPDIR == *"$NDIR/Games/Teamspeak"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Discord"* ]] ; then
if [ ! -d "$NDIR/Programs/$CS" ]; then
if [[ $CLI == *"0"* ]]; then
zenity --info --width=200 --window-icon=$ICO --title="$NAME $VER - $LNCH" --text="$LNCH is not installed."
exec $NAME
fi
echo -e "\e[40;38;5;82m$LNCH is not installed.\e[30;48;5;82m\e[0m"
exit
fi
fi

if [[ $CCKGPDIR == *"$NDIR/Games/Left 4 Gore"* ]]; then
if [ ! -d "$NDIR/Extras/left4gore-2.3-windows" ]; then
zenity --info --width=200 --window-icon=$ICO --title="$NAME $VER - $OTR" --text="$CS is not installed."
exec $NAME
fi
fi

if [[ $CCKGPDIR == *"$NDIR/Games/Steam"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Blizzard"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Origin"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Uplay"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Clone Hero"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Drakensang Online"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/itch"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Anarchy Online"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/GOG Galaxy"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/League of Legends"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Wargaming Game Center"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Wargaming Game Center"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Growtopia"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Bethesda Launcher"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Wargaming Game Center"* ]] || [[ $CCKGPDIR == *"$NDIR/Games/Arc"* ]] ; then
if [ ! -d "$NDIR/Games/$CS" ]; then
zenity --info --width=200 --window-icon=$ICO --title="$NAME $VER - $OTR" --text="$CS is not installed."
exec $NAME
fi
fi

if [ ! -d "/usr/home/$USER/.local/share/applications/Homura" ]; then
mkdir /usr/home/$USER/.local/share/applications/Homura
fi

if [[ $CS == *"Steam"* ]]; then
mkdir -p /usr/home/$USER/.local/share/applications/wine/Programs/$CS
if [ -f "/usr/home/$USER/.local/share/applications/wine/Programs/$CS/$CS.desktop" ]; then
rm /usr/home/$USER/.local/share/applications/wine/Programs/$CS/$CS.desktop
fi
echo "[Desktop Entry]
Name=$CS
Exec=$NAME Launch $CS
Type=Application
StartupNotify=true
Icon=BAC4_steam.0" >> /usr/home/$USER/.local/share/applications/wine/Programs/$CS/$CS.desktop
fi

if [[ $CS == *"Blizzard"* ]]; then
mkdir -p /usr/home/$USER/.local/share/applications/wine/Programs/Battle.net
if [ -f "/usr/home/$USER/.local/share/applications/wine/Programs/Battle.net/Battle.net.desktop" ]; then
rm /usr/home/$USER/.local/share/applications/wine/Programs/Battle.net/Battle.net.desktop
fi
echo "[Desktop Entry]
Name=$CS
Exec=$NAME Launch $CS
Type=Application
StartupNotify=true
Icon=65EF_Battle.net Launcher.0" >> /usr/home/$USER/.local/share/applications/wine/Programs/Battle.net/Battle.net.desktop
fi

if [[ $CS == *"Origin"* ]]; then
mkdir -p /usr/home/$USER/.local/share/applications/wine/Programs/$CS
if [ -f "/usr/home/$USER/.local/share/applications/wine/Programs/$CS/$CS.desktop" ]; then
rm /usr/home/$USER/.local/share/applications/wine/Programs/$CS/$CS.desktop
fi
echo "[Desktop Entry]
Name=$CS
Exec=$NAME Launch $CS
Type=Application
StartupNotify=true
Icon=9AD6_Origin.0" >> /usr/home/$USER/.local/share/applications/wine/Programs/$CS/$CS.desktop
fi

if [[ $CS == *"Uplay"* ]]; then
mkdir -p /usr/home/$USER/.local/share/applications/wine/Programs/Ubisoft/$CS
if [ -f "/usr/home/$USER/.local/share/applications/wine/Programs/Ubisoft/$CS/$CS.desktop" ]; then
rm /usr/home/$USER/.local/share/applications/wine/Programs/Ubisoft/$CS/$CS.desktop
fi
echo "[Desktop Entry]
Name=$CS
Exec=$NAME Launch $CS
Type=Application
StartupNotify=true
Icon=3B99_Uplay.0" >> /usr/home/$USER/.local/share/applications/wine/Programs/Ubisoft/$CS/$CS.desktop
fi

if [[ $CS == *"Teamspeak"* ]]; then
mkdir -p /usr/home/$USER/.local/share/applications/wine/Programs
if [ -f "/usr/home/$USER/.local/share/applications/wine/Programs/TeamSpeak 3 Client.desktop" ]; then
rm "/usr/home/$USER/.local/share/applications/wine/Programs/TeamSpeak 3 Client.desktop"
fi
echo "[Desktop Entry]
Name=$CS
Exec=$NAME Launch $CS
Type=Application
StartupNotify=true
Icon=0352_ts3client_win32.0" >> "/usr/home/$USER/.local/share/applications/wine/Programs/TeamSpeak 3 Client.desktop"
fi

if [[ $CS == *"Clone Hero"* ]]; then
cd $DDIR
curl -O https://clonehero.net/favicon.ico
if [ -f "/usr/home/$USER/.local/share/applications/$CS.desktop" ]; then
rm "/usr/home/$USER/.local/share/applications/$CS.desktop"
fi
echo "[Desktop Entry]
Name=$CS
Exec=$NAME Launch '$CS'
Type=Application
StartupNotify=true
Icon=$DDIR/favicon.ico" >> "/usr/home/$USER/.local/share/applications/$CS.desktop"
fi

if [[ $CS == *"Drakensang Online"* ]]; then
mkdir -p "/usr/home/$USER/.local/share/applications/wine/Programs/$CS"
if [ -f "/usr/home/$USER/.local/share/applications/wine/Programs/$CS/$CS.desktop" ]; then
rm "/usr/home/$USER/.local/share/applications/wine/Programs/$CS/$CS.desktop"
fi
echo "[Desktop Entry]
Name="$CS"
Exec=$NAME Launch '$CS'
Type=Application
StartupNotify=true
Icon=DA0A_icon" >> "/usr/home/$USER/.local/share/applications/wine/Programs/$CS/$CS.desktop"
fi

if [[ $CS == *"Anarchy Online"* ]]; then
zenity --info --width=350 --window-icon=$ICO --title="$NAME $VER - $CS" --text="We have told you to check/use the shortcut that the installer offer, sorry but no new shortcut for you!"
exec $NAME
fi

if [[ $CS == *"itch"* ]]; then
mkdir -p "/usr/home/$USER/.local/share/applications/wine/Programs/Itch Corp"
if [ -f "/usr/home/$USER/.local/share/applications/wine/Programs/Itch Corp/$CS.desktop" ]; then
rm "/usr/home/$USER/.local/share/applications/wine/Programs/Itch Corp/$CS.desktop"
fi
echo "[Desktop Entry]
Name=$CS
Exec=$NAME Launch $CS
Type=Application
StartupNotify=true
Icon=C840_itch-setup.0" >> "/usr/home/$USER/.local/share/applications/wine/Programs/Itch Corp/$CS.desktop"
fi

if [[ $CS == *"GOG Galaxy"* ]]; then
mkdir -p "/usr/home/$USER/.local/share/applications/wine/Programs/GOG.com/GOG Galaxy"
if [ -f "/usr/home/$USER/.local/share/applications/wine/Programs/GOG.com/GOG Galaxy/$CS.desktop" ]; then
rm "/usr/home/$USER/.local/share/applications/wine/Programs/GOG.com/GOG Galaxy/$CS.desktop"
fi
echo "[Desktop Entry]
Name="$CS"
Exec=$NAME Launch '$CS'
Type=Application
StartupNotify=true
Icon=F77E_GalaxyClient.0" >> "/usr/home/$USER/.local/share/applications/wine/Programs/GOG.com/GOG Galaxy/$CS.desktop"
fi

if [[ $CS == *"League of Legends"* ]]; then
cd $DDIR
curl -O http://2.bp.blogspot.com/-HqSOKIIV59A/U8WP4WFW28I/AAAAAAAAT5U/qTSiV9UgvUY/s1600/icon.png
if [ -f "/usr/home/$USER/.local/share/applications/$CS.desktop" ]; then
rm "/usr/home/$USER/.local/share/applications/$CS.desktop"
fi
echo "[Desktop Entry]
Name=$CS
Exec=$NAME Launch '$CS'
Type=Application
StartupNotify=true
Icon=$DDIR/icon.png" >> "/usr/home/$USER/.local/share/applications/$CS.desktop"
fi

if [[ $CS == *"Wargaming Game Center"* ]]; then
mkdir -p /usr/home/$USER/.local/share/applications/wine/Programs/Wargaming.net
if [ -f "/usr/home/$USER/.local/share/applications/wine/Programs/Wargaming.net/Wargaming.net Game Center.desktop" ]; then
rm "/usr/home/$USER/.local/share/applications/wine/Programs/Wargaming.net/Wargaming.net Game Center.desktop"
fi
echo "[Desktop Entry]
Name=$CS
Exec=$NAME Launch '$CS'
Type=Application
StartupNotify=true
Icon=3CE7_wgc.0" >> "/usr/home/$USER/.local/share/applications/wine/Programs/Wargaming.net/Wargaming.net Game Center.desktop"
fi

if [[ $CS == *"Growtopia"* ]]; then
mkdir -p /usr/home/$USER/.local/share/applications/wine/Programs/$CS
if [ -f "/usr/home/$USER/.local/share/applications/wine/Programs/$CS/$CS.desktop" ]; then
rm "/usr/home/$USER/.local/share/applications/wine/Programs/$CS/$CS.desktop"
fi
echo "[Desktop Entry]
Name=$CS
Exec=$NAME Launch $CS
Type=Application
StartupNotify=true
Icon=B09A_Growtopia.0" >> /usr/home/$USER/.local/share/applications/wine/Programs/$CS/$CS.desktop
fi

if [[ $CS == *"Bethesda Launcher"* ]]; then
mkdir -p "/usr/home/$USER/.local/share/applications/wine/Programs/Bethesda.net Launcher"
if [ -f "/usr/home/$USER/.local/share/applications/wine/Programs/Bethesda.net Launcher/Bethesda.net Launcher.desktop" ]; then
rm "/usr/home/$USER/.local/share/applications/wine/Programs/Bethesda.net Launcher/Bethesda.net Launcher.desktop"
fi
echo "[Desktop Entry]
Name="$CS"
Exec=$NAME Launch '$CS'
Type=Application
StartupNotify=true
Icon=5C20_BethesdaNetUpdater.0" >> "/usr/home/$USER/.local/share/applications/wine/Programs/Bethesda.net Launcher/Bethesda.net Launcher.desktop"
fi

if [[ $CS == *"Arc"* ]]; then
mkdir -p "/usr/home/$USER/.local/share/applications/wine/Programs/Perfect World Entertainment/$CS"
if [ -f "/usr/home/$USER/.local/share/applications/wine/Programs/Perfect World Entertainment/$CS/$CS.desktop" ]; then
rm /usr/home/$USER/.local/share/applications/wine/Programs/Perfect World Entertainment/$CS/$CS.desktop
fi
echo "[Desktop Entry]
Name=$CS
Exec=$NAME Launch $CS
Type=Application
StartupNotify=true
Icon=403B_ArcLauncher.0" >> "/usr/home/$USER/.local/share/applications/wine/Programs/Perfect World Entertainment/$CS/$CS.desktop"
fi

if [[ $CS == *"Discord"* ]]; then
if [ -f "/usr/home/$USER/.local/share/applications/$CS.desktop" ]; then
rm /usr/home/$USER/.local/share/applications/$CS.desktop
fi
echo "[Desktop Entry]
Name=$CS
Exec=$NAME Launch $CS
Type=Application
StartupNotify=true
Icon=NDIR/Programs/$CS/$CS/app.ico" >> /usr/home/$USER/.local/share/applications/$CS.desktop
fi

if [[ $CS == *"Left 4 Gore"* ]]; then
cd $DDIR
curl -O http://www.left4gore.com/favicon.ico
mv favicon.ico favicon_lf4g.ico
if [ -f "/usr/home/$USER/.local/share/applications/$CS.desktop" ]; then
rm /usr/home/$USER/.local/share/applications/$CS.desktop
fi
echo "[Desktop Entry]
Name="$CS"
Exec=$NAME Launch '$CS'
Type=Application
StartupNotify=true
Icon=$DDIR/favicon_lf4g.ico" >> "/usr/home/$USER/.local/share/applications/$CS.desktop"
fi

if [[ $CS == *"Custom Prefix"* ]]; then
if [ ! "$(ls -A "/usr/home/$USER/.local/share/$NAME/Custom Prefixes")" ]
then
zenity --info --width=310 --window-icon=$ICO --title="$NAME $VER - $LNCH" --text="There is no custom prefix installed"
else
cd "$NDIR/Custom Prefixes"
PREFIXNAME=$(zenity --file-selection --directory --title="Choose your prefix" --filename="/usr/home/$USER/.local/share/$NAME/Custom Prefixes/")
if [ -z "$PREFIXNAME" ]
then
zenity --info --width=310 --window-icon=$ICO --title="$NAME $VER - $TODO" --text="There was no custom prefix selected."
else
SCNAME=$(zenity --window-icon=$ICO --title="Create a custom prefix shortcut" --text "How your shortcut should be called?" --entry --width=260) 
SCICO="$(zenity --file-selection --title="Choose an icon")"
if [ -f "/usr/home/$USER/.local/share/applications/$SCNAME.desktop" ]; then
rm /usr/home/$USER/.local/share/applications/$SCNAME.desktop
fi
echo "[Desktop Entry]
Name="$SCNAME"
Exec=bash '$PREFIXNAME/start.sh'
Type=Application
StartupNotify=true
Icon=$SCICO" >> "/usr/home/$USER/.local/share/applications/$SCNAME.desktop"
fi
fi
fi
fi

if [[ $OTR == *"GitHub page"* ]]; then
xdg-open https://github.com/the-homura-project/homura
fi
fi

if [[ $TODO == *"About"* ]]; then
zenity --info --window-icon=$ICO --width=390 --title="$NAME $VER - About" --text="Inspired by Lutris.
$NAME is a launcher that makes it easy to run Windows games/launcher easily on FreeBSD by providing the required fixes and workarounds. 
The Windows emulation is provided by Wine.
$NAME is licensed under the BSD 2-Clause License.
Copyright (c) 2019-2020, The Homura Project
All rights reserved."
fi

if [[ $TODO == *"Exit"* ]]; then
zenity --notification --window-icon=$ICO --text "Thanks for using $NAME and have a great day!"
exit
fi
zenity --notification --window-icon=$ICO --text "Task completed or application closed!"
if [[ $CLI == *"0"* ]]; then
exec $NAME
fi
